# Generated by Django 5.0.13 on 2026-08-15 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clustering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genai_labels_model', models.TextField()),
                ('genai_labels_prompt', models.TextField(null=True)),
                ('genai_article_model', models.TextField()),
                ('genai_article_prompt', models.TextField(null=True)),
                ('clustering_options', models.JSONField()),
                ('clustering_method', models.TextField()),
                ('reducer_method', models.TextField()),
                ('reducer_optimizer', models.TextField()),
                ('reducer_similarity', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContinuousInformationGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_created', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('has_sub_graphs', models.BooleanField(default=True)),
                ('graph_directory', models.TextField(null=True)),
                ('graph_file_name', models.TextField(null=True)),
                ('info', models.JSONField(default=dict, null=True)),
                ('summary', models.JSONField(default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FullGeneratedArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_str', models.TextField()),
                ('generation_time', models.DurationField()),
                ('model_used_to_generate', models.TextField()),
                ('when_generated', models.DateTimeField(auto_now=True)),
                ('user_query', models.TextField()),
                ('based_on_news', models.JSONField()),
                ('article_type', models.TextField(null=True)),
                ('sse_query_response_id', models.TextField(null=True)),
                ('language', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('display_name', models.TextField()),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SampleClusterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('news_urls', models.JSONField()),
                ('news_metadata', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField()),
                ('size', models.IntegerField()),
                ('label_str', models.TextField()),
                ('description', models.TextField(null=True)),
                ('is_outlier', models.BooleanField()),
                ('article_text', models.TextField()),
                ('stats', models.JSONField()),
                ('news_urls', models.JSONField()),
                ('news_metadata', models.JSONField()),
                ('sample_indices', models.JSONField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('has_next_similarity', models.BooleanField(default=False)),
                ('has_prev_similarity', models.BooleanField(default=False)),
                ('clustering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.clustering')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='creator.sampleclusterdata')),
            ],
        ),
        migrations.CreateModel(
            name='ContinuousInformationSubGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_created', models.DateTimeField(auto_now=True)),
                ('sub_graph_directory', models.TextField(null=True)),
                ('sub_graph_file_name', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('comment', models.TextField(null=True)),
                ('article', models.TextField(null=True)),
                ('type_str', models.TextField(default='')),
                ('info', models.JSONField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.TextField()),
                ('label_str', models.TextField()),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='continuous_sub_graph', to='creator.continuousinformationgraph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_url', models.URLField()),
                ('begin_crawling_url', models.URLField()),
                ('min_news_depth', models.IntegerField()),
                ('last_check', models.DateTimeField(null=True)),
                ('index_page', models.BooleanField(default=False)),
                ('index_page_sse', models.BooleanField(default=False)),
                ('prepare_news', models.BooleanField(default=False)),
                ('show_news', models.BooleanField(default=False)),
                ('use_heuristic_to_extract_news_content', models.BooleanField(default=False)),
                ('use_heuristic_to_search_news_content', models.BooleanField(default=False)),
                ('use_heuristic_to_clear_news_content', models.BooleanField(default=False)),
                ('news_link_starts_with_main_url', models.BooleanField(default=False)),
                ('include_paths_with', models.JSONField(default=list)),
                ('exclude_paths_with', models.JSONField(default=list)),
                ('news_url_ends_with', models.JSONField(default=list)),
                ('single_news_content_tag_name', models.TextField(null=True)),
                ('single_news_content_tag_attr_name', models.TextField(null=True)),
                ('single_news_content_tag_attr_value', models.TextField(null=True)),
                ('remove_n_last_elems', models.IntegerField(default=0, null=True)),
                ('language', models.TextField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.newscategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='system.systemuser')),
            ],
        ),
        migrations.CreateModel(
            name='MainNewsPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_crawled', models.DateTimeField(auto_now=True)),
                ('content_hash', models.TextField()),
                ('html_content', models.TextField()),
                ('extracted_urls', models.JSONField(default=list)),
                ('main_page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.newsmainpage')),
            ],
        ),
        migrations.CreateModel(
            name='NewsSubPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_url', models.TextField()),
                ('when_crawled', models.DateTimeField(auto_now=True)),
                ('page_content_html', models.TextField()),
                ('page_content_txt', models.TextField()),
                ('page_content_txt_translated', models.TextField(null=True)),
                ('skip_subpage', models.BooleanField(default=False)),
                ('has_generated_news', models.BooleanField(default=False)),
                ('is_indexed_in_sse', models.BooleanField(default=False)),
                ('num_of_generated_news', models.IntegerField(default=0)),
                ('main_page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.newsmainpage')),
            ],
            options={
                'unique_together': {('news_url', 'main_page')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_text', models.TextField()),
                ('generation_time', models.DurationField()),
                ('language', models.TextField(null=True)),
                ('model_used_to_generate_news', models.TextField()),
                ('show_news', models.BooleanField(default=True)),
                ('polarity_3c', models.CharField(max_length=32, null=True)),
                ('polarity_3c_logits', models.JSONField(null=True)),
                ('pli_value', models.FloatField(null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('when_generated', models.DateTimeField(auto_now=True)),
                ('similarity_to_original', models.FloatField(null=True)),
                ('show_admin_message', models.BooleanField(default=True)),
                ('news_sub_page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.newssubpage')),
            ],
        ),
        migrations.CreateModel(
            name='SingleDaySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_to_summary', models.DateField()),
                ('when_generated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clustering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.clustering')),
            ],
        ),
        migrations.CreateModel(
            name='ClustersInContinuousInformationSubGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_created', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.cluster')),
                ('sub_graph', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clusters_in_continuous_sub_graph', to='creator.continuousinformationsubgraph')),
            ],
            options={
                'unique_together': {('cluster', 'sub_graph')},
            },
        ),
        migrations.CreateModel(
            name='SimilarClusters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_value', models.FloatField()),
                ('similarity_metric', models.TextField()),
                ('similarity_model', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clustering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.clustering')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_cluster', to='creator.cluster')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_cluster', to='creator.cluster')),
            ],
            options={
                'unique_together': {('source', 'target', 'clustering')},
            },
        ),
    ]
