# Generated by Django 5.0.6 on 2024-06-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newscategory",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="newsmainpage",
            name="index_page",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newsmainpage",
            name="index_page_sse",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newsmainpage",
            name="show_news",
            field=models.BooleanField(default=False),
        ),
    ]
