# Generated by Django 5.0.6 on 2024-06-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0002_newscategory_order_newsmainpage_index_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsmainpage",
            name="use_heuristic_to_clear_news_content",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newsmainpage",
            name="use_heuristic_to_search_news_content",
            field=models.BooleanField(default=False),
        ),
    ]
