# Generated by Django 5.0.6 on 2024-06-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "creator",
            "0003_newsmainpage_use_heuristic_to_clear_news_content_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="generatednews",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="generatednews",
            name="polarity_3c",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="generatednews",
            name="polarity_3c_logits",
            field=models.JSONField(null=True),
        ),
    ]
