# Generated by Django 5.0.6 on 2024-06-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "creator",
            "0004_generatednews_metadata_generatednews_polarity_3c_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="generatednews",
            name="pli_value",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="generatednews",
            name="when_generated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
