# Generated by Django 5.0.6 on 2024-07-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0005_generatednews_pli_value_generatednews_when_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatednews",
            name="similarity_to_original",
            field=models.FloatField(null=True),
        ),
    ]
