# Generated by Django 5.0.6 on 2024-07-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0006_generatednews_similarity_to_original"),
    ]

    operations = [
        migrations.AddField(
            model_name="newssubpage",
            name="skip_subpage",
            field=models.BooleanField(default=False),
        ),
    ]
