# Generated by Django 5.0.6 on 2024-07-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0007_newssubpage_skip_subpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="newssubpage",
            name="num_of_generated_news",
            field=models.IntegerField(default=0),
        ),
    ]
