# Generated by Django 5.0.6 on 2024-07-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0008_newssubpage_num_of_generated_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatednews",
            name="language",
            field=models.TextField(null=True),
        ),
    ]
