# Generated by Django 5.0.6 on 2024-07-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0009_generatednews_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsmainpage",
            name="remove_n_last_elems",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="newsmainpage",
            name="single_news_content_tag_class",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="newsmainpage",
            name="single_news_content_tag_name",
            field=models.TextField(null=True),
        ),
    ]
