# Generated by Django 5.0.6 on 2024-07-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0010_newsmainpage_remove_n_last_elems_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newssubpage",
            name="news_url",
            field=models.TextField(),
        ),
    ]
