# Generated by Django 5.0.6 on 2024-07-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0011_alter_newssubpage_news_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsmainpage",
            old_name="single_news_content_tag_class",
            new_name="single_news_content_tag_attr_name",
        ),
        migrations.AddField(
            model_name="newsmainpage",
            name="single_news_content_tag_attr_value",
            field=models.TextField(null=True),
        ),
    ]
