# Generated by Django 5.0.6 on 2024-07-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "creator",
            "0012_rename_single_news_content_tag_class_newsmainpage_single_news_content_tag_attr_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="generatednews",
            name="show_admin_message",
            field=models.BooleanField(default=True),
        ),
    ]
