# Generated by Django 5.0.6 on 2024-09-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0013_generatednews_show_admin_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="FullGeneratedArticles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_str", models.TextField()),
                ("generation_time", models.DurationField()),
                ("model_used_to_generate", models.TextField()),
                ("when_generated", models.DateTimeField(auto_now=True)),
                ("user_query", models.TextField()),
                ("based_on_news", models.JSONField()),
                ("article_type", models.TextField(null=True)),
                ("sse_query_response_id", models.TextField(null=True)),
                ("language", models.TextField(null=True)),
            ],
        ),
    ]
