# Generated by Django 5.0.6 on 2025-05-25 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0014_fullgeneratedarticles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clustering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genai_labels_model", models.TextField()),
                ("genai_article_model", models.TextField()),
                ("clustering_options", models.JSONField()),
                ("clustering_method", models.TextField()),
                ("reducer_method", models.TextField()),
                ("reducer_optimizer", models.TextField()),
                ("reducer_similarity", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SampleClusterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.IntegerField()),
                ("news_urls", models.JSONField()),
                ("news_metadata", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.IntegerField()),
                ("size", models.IntegerField()),
                ("label_str", models.TextField()),
                ("description", models.TextField(null=True)),
                ("is_outlier", models.BooleanField()),
                ("article_text", models.TextField()),
                ("stats", models.JSONField()),
                ("news_urls", models.JSONField()),
                ("news_metadata", models.JSONField()),
                (
                    "clustering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="creator.clustering",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="creator.sampleclusterdata",
                    ),
                ),
            ],
        ),
    ]
