# Generated by Django 4.2 on 2025-05-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0015_clustering_sampleclusterdata_cluster"),
    ]

    operations = [
        migrations.AddField(
            model_name="clustering",
            name="genai_article_prompt",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="clustering",
            name="genai_labels_prompt",
            field=models.TextField(null=True),
        ),
    ]
