# Generated by Django 4.2 on 2025-05-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0016_clustering_genai_article_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="sample_indices",
            field=models.JSONField(null=True),
        ),
    ]
