# Generated by Django 5.0.6 on 2025-05-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0017_cluster_is_active_clustering_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='has_next_similarity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cluster',
            name='has_prev_similarity',
            field=models.BooleanField(default=False),
        ),
    ]
