# Generated by Django 4.2 on 2025-05-25 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0017_cluster_sample_indices"),
    ]

    operations = [
        migrations.CreateModel(
            name="SingleDaySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_to_summary", models.DateField()),
                ("when_generated", models.DateTimeField(auto_now=True)),
                (
                    "clustering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="creator.clustering",
                    ),
                ),
            ],
        ),
    ]
