# Generated by Django 5.0.6 on 2025-06-01 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0018_cluster_has_next_similarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarclusters',
            name='clustering',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='creator.clustering'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='similarclusters',
            unique_together={('source', 'target', 'clustering')},
        ),
    ]
