# Generated by Django 5.0.6 on 2025-06-02 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0018_singledaysummary"),
        ("creator", "0019_similarclusters_clustering_and_more"),
    ]

    operations = []
