# Generated by Django 5.0.6 on 2025-06-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0020_merge_20250602_0052"),
    ]

    operations = [
        migrations.AddField(
            model_name="singledaysummary",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
