# Generated by Django 5.0.6 on 2025-06-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0023_continuousinformationgraph_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuousinformationsubgraph',
            name='sub_graph_directory',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='continuousinformationsubgraph',
            name='sub_graph_file_name',
            field=models.TextField(null=True),
        ),
    ]
