# Generated by Django 5.0.6 on 2025-06-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "creator",
            "0024_continuousinformationsubgraph_sub_graph_directory_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="continuousinformationsubgraph",
            name="label",
            field=models.TextField(),
        ),
    ]
