# Generated by Django 5.0.6 on 2025-06-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0025_alter_continuousinformationsubgraph_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="continuousinformationsubgraph",
            name="type_str",
            field=models.TextField(default=""),
        ),
    ]
