# Generated by Django 5.0.13 on 2026-08-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0026_continuousinformationsubgraph_type_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssubpage',
            name='page_content_txt_translated',
            field=models.TextField(null=True),
        ),
    ]
