# Generated by Django 5.0.13 on 2026-08-15 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlesStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statistics_date", models.DateTimeField(auto_now_add=True)),
                ("pages_statistics", models.JSONField()),
                ("polarity_statistics", models.JSONField()),
                ("are_actual", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PublicSSESettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news_collection_name", models.TextField()),
                ("news_collection_description", models.TextField()),
                ("news_collection_display_name", models.TextField()),
                ("news_embedder_index_type", models.TextField()),
                ("news_embedder_model_name", models.TextField()),
                ("news_embedder_model_size", models.IntegerField()),
                ("news_reranker_model_name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actual_settings", models.BooleanField()),
                ("settings_date", models.DateTimeField(auto_now_add=True)),
                ("doing_news_indexing", models.BooleanField(default=False)),
                ("doing_news_summarization", models.BooleanField(default=False)),
                ("doing_news_semantic_indexing", models.BooleanField(default=False)),
                ("doing_news_polarity_3c_check", models.BooleanField(default=False)),
                ("doing_news_pli_check", models.BooleanField(default=False)),
                ("doing_news_publ_stats", models.BooleanField(default=False)),
                (
                    "doing_news_generation_for_yesterday",
                    models.BooleanField(default=False),
                ),
                (
                    "doing_news_generation_for_yesterday_similarity",
                    models.BooleanField(default=False),
                ),
                ("doing_news_information_graph", models.BooleanField(default=False)),
                (
                    "doing_news_information_sub_graph",
                    models.BooleanField(default=False),
                ),
                ("last_news_indexing_check_begin", models.DateTimeField(null=True)),
                ("last_news_indexing_check_end", models.DateTimeField(null=True)),
                (
                    "last_news_summarization_check_begin",
                    models.DateTimeField(null=True),
                ),
                (
                    "last_news_summarization_check_end",
                    models.DateTimeField(null=True),
                ),
                (
                    "last_news_semantic_indexing_check_begin",
                    models.DateTimeField(null=True),
                ),
                (
                    "last_news_semantic_indexing_check_end",
                    models.DateTimeField(null=True),
                ),
                (
                    "last_news_polarity_3c_check_begin",
                    models.DateTimeField(null=True),
                ),
                ("last_news_polarity_3c_check_end", models.DateTimeField(null=True)),
                ("last_news_pli_check_begin", models.DateTimeField(null=True)),
                ("last_news_pli_check_end", models.DateTimeField(null=True)),
                (
                    "last_news_publ_stats_check_begin",
                    models.DateTimeField(null=True),
                ),
                ("last_news_publ_stats_check_end", models.DateTimeField(null=True)),
                (
                    "last_news_generation_for_yesterday_begin",
                    models.DateTimeField(null=True),
                ),
                (
                    "last_news_generation_for_yesterday_end",
                    models.DateTimeField(null=True),
                ),
                (
                    "last_news_generation_for_yesterday_similarity_begin",
                    models.DateTimeField(null=True),
                ),
                (
                    "last_news_generation_for_yesterday_similarity_end",
                    models.DateTimeField(null=True),
                ),
                (
                    "last_news_information_graph_begin",
                    models.DateTimeField(null=True),
                ),
                ("last_news_information_graph_end", models.DateTimeField(null=True)),
                (
                    "last_news_information_sub_graph_begin",
                    models.DateTimeField(null=True),
                ),
                (
                    "last_news_information_sub_graph_end",
                    models.DateTimeField(null=True),
                ),
                (
                    "last_articles_stats",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system.articlesstatistics",
                    ),
                ),
                (
                    "public_stream_news_sse_settings",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system.publicssesettings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auth_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
