# Generated by Django 5.0.6 on 2024-07-20 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_systemsettings_doing_news_pli_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics_date', models.DateTimeField(auto_now_add=True)),
                ('pages_statistics', models.JSONField()),
                ('polarity_3c_statistics', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='last_articles_stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.articlesstatistics'),
        ),
    ]
