# Generated by Django 5.0.6 on 2025-06-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "system",
            "0006_systemsettings_doing_news_generation_for_yesterday_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="doing_news_generation_for_yesterday_similarity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="last_news_generation_for_yesterday_similarity_begin",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="last_news_generation_for_yesterday_similarity_end",
            field=models.DateTimeField(null=True),
        ),
    ]
