# Generated by Django 5.0.6 on 2025-06-21 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0008_systemsettings_doing_information_graph_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="systemsettings",
            old_name="doing_information_graph",
            new_name="doing_news_information_graph",
        ),
    ]
