# Generated by Django 5.0.6 on 2025-06-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_rename_doing_information_graph_systemsettings_doing_news_information_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='doing_news_information_sub_graph',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='last_news_information_sub_graph_begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='last_news_information_sub_graph_end',
            field=models.DateTimeField(null=True),
        ),
    ]
