#!/bin/bash

export PLAYGROUND_PUBLIC_USER_NAME=xyz
export PLAYGROUND_PUBLIC_USER_PASS=xyz

APP_FILE=prepare_public_statistics.py
MAIN_DIR=/mnt/data2/dev/develop/radlab-article-creator

MAIN_PROJECT_DIR=${MAIN_DIR}/article_creator
PERIODIC_APPS_DIR=${MAIN_PROJECT_DIR}/apps_creator/periodic

APP_FILE_PATH_PERIODIC_APPS_DIR="${PERIODIC_APPS_DIR}/${APP_FILE}"
APP_FILE_PATH_MAIN_PROJECT_DIR="${MAIN_PROJECT_DIR}/${APP_FILE}"

cp "${APP_FILE_PATH_PERIODIC_APPS_DIR}" ${APP_FILE_PATH_MAIN_PROJECT_DIR}

cd "${MAIN_PROJECT_DIR}" || return

python3 "${APP_FILE_PATH_MAIN_PROJECT_DIR}"
rm "${APP_FILE_PATH_MAIN_PROJECT_DIR}"
