#!/bin/bash

export PLAYGROUND_PUBLIC_USER_NAME=XYZ
export PLAYGROUND_PUBLIC_USER_PASS=XYZ

export CUDA_VISIBLE_DEVICES=1

export CROSS_ENCODER_DEVICE="cuda:0"

APP_FILE=generate_news_for_public_stream.py

MAIN_PROJECT_DIR=$(pwd)
PERIODIC_APPS_DIR=${MAIN_PROJECT_DIR}/apps_creator/periodic

APP_FILE_PATH_PERIODIC_APPS_DIR="${PERIODIC_APPS_DIR}/${APP_FILE}"
APP_FILE_PATH_MAIN_PROJECT_DIR="${MAIN_PROJECT_DIR}/${APP_FILE}"

cp "${APP_FILE_PATH_PERIODIC_APPS_DIR}" "${APP_FILE_PATH_MAIN_PROJECT_DIR}"

cd "${MAIN_PROJECT_DIR}" || return

python3 "${APP_FILE_PATH_MAIN_PROJECT_DIR}" \
  --begin-date="2026-01-01" \
  --end-date="2026-01-31" \
  --dont-shuffle

# python3 "${APP_FILE_PATH_MAIN_PROJECT_DIR}"
rm "${APP_FILE_PATH_MAIN_PROJECT_DIR}"
